## Grouping and Aggregating with Pandas

When working with large datasets it's used to group and summarize the data to make analysis easier. Pandas a popular Python library provides powerful tools for this. In this article you'll learn how to use Pandas' groupby() and aggregation functions step by step with clear explanations and practical examples.

### Aggregation in Pandas
Aggregation means applying a mathematical function to summarize data. It can be used to get a summary of columns in our dataset like getting sum, minimum, maximum etc. from a particular column of our dataset. The function used for aggregation is agg() the parameter is the function we want to perform. Some functions used in the aggregation are:

Function        	Description
- sum()	Compute sum of column values
- min()	Compute min of column values
- max()	Compute max of column values
- mean()	Compute mean of column
- size()	Compute column sizes
- describe() Generates descriptive statistics
- first()	Compute first of group values
- last()	Compute last of group values
- count()	Compute count of column values
- std()	Standard deviation of column
- var()	Compute variance of column
- sem()	Standard error of the mean of column

In [1]:
import pandas as pd

df = pd.DataFrame([[9, 4, 8, 9],
                   [8, 10, 7, 6],
                   [7, 6, 8, 5]],
                  columns=['Maths',  'English', 
                           'Science', 'History'])

print(df)

   Maths  English  Science  History
0      9        4        8        9
1      8       10        7        6
2      7        6        8        5

#### 1. Summing Up All Values (sum())
The sum() function adds up all values in each column.

In [2]:
df.sum()

Maths      24
English    20
Science    23
History    20
dtype: int64

#### 2. Getting a Summary (describe())
Instead of calculating sum, mean, min and max separately we can use describe() which provides all important statistics in one go.

In [3]:
df.describe()

       Maths    English   Science   History
count    3.0   3.000000  3.000000  3.000000
mean     8.0   6.666667  7.666667  6.666667
std      1.0   3.055050  0.577350  2.081666
min      7.0   4.000000  7.000000  5.000000
25%      7.5   5.000000  7.500000  5.500000
50%      8.0   6.000000  8.000000  6.000000
75%      8.5   8.000000  8.000000  7.500000
max      9.0  10.000000  8.000000  9.000000

#### 3. Applying Multiple Aggregations at Once (agg())
The .agg() function lets you apply multiple aggregation functions at the same time.

In [4]:
df.agg(['sum', 'min', 'max'])

     Maths  English  Science  History
sum     24       20       23       20
min      7        4        7        5
max      9       10        8        9

### Grouping in Pandas
Grouping in Pandas means organizing your data into groups based on some columns. Once grouped you can perform actions like finding the total, average, count or even pick the first row from each group. This method follows a split-apply-combine process:

- Split the data into groups
- Apply some calculation like sum, average etc.
- Combine the results into a new table.

In [9]:
import pandas as pd

data = {
    'Item': ['Cake', 'Cake', 'Bread', 'Pastry', 'Cake'],
    'Flavor': ['Chocolate', 'Vanilla', 'Whole Wheat', 'Strawberry', 'Chocolate'],
    'Price': [250, 220, 80, 120, 350]
}

df = pd.DataFrame(data)
print(df)

     Item       Flavor  Price
0    Cake    Chocolate    250
1    Cake      Vanilla    220
2   Bread  Whole Wheat     80
3  Pastry   Strawberry    120
4    Cake    Chocolate    350

#### 1. Grouping Data by One Column Using groupby()
Let’s say we want to group the orders based on the Item column.

In [6]:
grouped = df.groupby('Item')
print(grouped)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x00000162D82A9F10>

This doesn't show the result directly it just creates a grouped object. To actually see the data we need to apply a method like .sum(), .mean() or first(). Let’s find the total price of each item sold:

In [7]:
print(df.groupby('Item')['Price'].sum())

Item
Bread      80
Cake      720
Pastry    120
Name: Price, dtype: int64

In [11]:
df.groupby('Flavor')['Price'].max()

Flavor
Chocolate      350
Strawberry     120
Vanilla        220
Whole Wheat     80
Name: Price, dtype: int64

#### 2. Grouping by Multiple Columns
Now let’s group by Item and Flavor to see how each flavored item sold.

In [12]:
print(df.groupby(['Item', 'Flavor'])['Price'].sum())

Item    Flavor
Bread   Whole Wheat     80
Cake    Chocolate      600
        Vanilla        220
Pastry  Strawberry     120
Name: Price, dtype: int64